services:
  scraping-api:
    build:
      context: ./API_scraping
      dockerfile: Dockerfile
    image: pubmed-scraping-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=development

  preprocessing-api:
    build:
      context: ./API_preprocessed
      dockerfile: Dockerfile
    image: pubmed-preprocessing-api
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    depends_on:
      - scraping-api

networks:
  scraper-net:
    driver: bridge