version: '3'

services:
  scraping-api:
    build:
      context: .
      dockerfile: API_Scraping/Dockerfile
    image: pubmed-scraping-api
    ports:
      - "5000:5000"
    volumes:
      - ./shared/data:/app/data
      - ./shared_data:/app/shared_data
    environment:
      - FLASK_ENV=development
    networks:
      - scraper-net

  preprocessing-api:
    build:
      context: .
      dockerfile: API_preprocessed/Dockerfile
    volumes:
      - ./shared/data:/app/data
      - ./journal_scraper:/app/journal_scraper
      - ./shared_data:/app/shared_data
      - ./models:/app/models
    ports:
      - "5001:5001"
    depends_on:
      - scraping-api
    networks:
      - scraper-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - scraper-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - scraper-net
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource,dalvany-image-panel

volumes:
  grafana-storage:

networks:
  scraper-net:
    driver: bridge
