services:
  scraping-api:
    build:
      context: .
      dockerfile: API_Scraping/Dockerfile
    image: pubmed-scraping-api
    ports:
      - "5000:5000"
    volumes:
      - ./shared/data:/app/data
      - ./Hasil Scraping:/app/shared_data
    environment:
      - FLASK_ENV=development

  preprocessing-api:
    build:
      context: .
      dockerfile: API_preprocessed/Dockerfile
    volumes:
      - ./shared/data:/app/data
      - ./journal_scraper:/app/journal_scraper
      - ./Hasil Scraping:/app/shared_data
      - ./models:/app/models
    
    ports:
      - "5001:5001"

    depends_on:
      - scraping-api

networks:
  scraper-net:
    driver: bridge